name: deploy.yml

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  multi-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [dev, staging, production]
      max-parallel: 1
    environment: ${{ matrix.stage }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: config jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: build
        env:
          AMBIENTE_ATUAL: ${{ matrix.stage }}
          MINHA_SENHA: ${{ secrets.DB_PASSWORD }}
          MEU_USUARIO: ${{ secrets.DB_USER }}
        run: |
          mvn clean package
          
          echo "usando credencial secret do ambiente $AMBIENTE_ATUAL. SENHA: $MINHA_SENHA"
          echo "usando credencial secret do ambiente $AMBIENTE_ATUAL. USUARIO $MEU_USER"

      - name: upload arquivo .jar
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: target/*.jar

      - name: log ambiente atual
        run: echo "Deploy simulado em ambiente $AMBIENTE_ATUAL finalizado."