name: deploy.yml

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: config jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Compilar (Maven)
        run: mvn clean package

      - name: upload jar
        uses: actions/upload-artifact@v4
        with:
          name: app-build-final
          path: target/*.jar

  multi-deploy:
    name: deploy em ambientes
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [dev, staging, production]
      max-parallel: 1
    environment: ${{ matrix.stage }}

    steps:
      - name: download jar
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Simular Deploy
        env:
          AMBIENTE_ATUAL: ${{ matrix.stage }}
          MINHA_SENHA: ${{ secrets.DB_PASSWORD }}
          MEU_USUARIO: ${{ secrets.DB_USER }}
        run: |          
          echo "simulando deploy no ambiente: $AMBIENTE_ATUAL"
          echo "usando secret DB_USER: $MEU_USUARIO"
          echo "usando secret DB_PASSWORD: $MINHA_SENHA"